version: '3.9'

services:
#  backend:

  apache:
    image: ubuntu/apache2
    volumes:
      - /srv/docker/angular/UNDECIDED-UI/apache.conf:/etc/apache2/sites-enabled
      - /srv/docker/angular/UNDECIDED-UI/dist:/var/www/html
    ports:
      - "81:80"
    networks:
      - web

#  db:
#    image:




networks:
  web:
  db:
