version: '3.9'

services:


  backend:
    build: .
    container_name: spring
    image: spring
#      context: /srv/docker/spring/UNDECIDED
#      args:
#        version: 0.1
#    working_dir: /undecided
#    volumes:
#      - /srv/docker/spring/spring/UNDECIDED/target/UNDECIDED-0.1.jar:/undecided/undecided.jar
#    command: "java -jar /undecided.jar"
    expose:
     - "8080"
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.entrypoints=web"
      - "traefik.http.routers.spring.rule=PathPrefix(`/api`)"
#    networks:
#      - web
#      - db

  apache:
    image: ubuntu/apache2
    container_name: apache
    volumes:
      - /srv/docker/angular/UNDECIDED-UI/apache.conf:/etc/apache2/sites-enabled/001-page.conf
      - /srv/docker/angular/UNDECIDED-UI/dist/UI:/var/www/html
#    ports:
#      - "81:80"
#    networks:
#      - web
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.entrypoints=apache"
      - "traefik.http.routers.apache.rule=PathPrefix(`/`)"
#     depends_on:
#      - backend

  traefik:
    image: "traefik:v2.5"
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "81:80"
      - "8889:8080"
#    networks:
#      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


#  db:
#    image:




#networks:
#  web:
#  db:
