version: '3.9'

services:


  backend:
    image: openjdk:11
    volumes:
    - /srv/docker/spring/spring/UNDECIDED/target/UNDECIDED-01.jar:./undecided.jar
    command: "java -jar undecided.jar"
    expose:
      - "80"
    networks:
      -web
      -db

  apache:
    image: ubuntu/apache2
    volumes:
      - /srv/docker/angular/UNDECIDED-UI/apache.conf:/etc/apache2/sites-enabled
      - /srv/docker/angular/UNDECIDED-UI/dist:/var/www/html
    ports:
      - "81:80"
    networks:
      - web

#  db:
#    image:




networks:
  web:
  db:
