version:'3'

services: 


  backend:
    build: .
    image: spring
    ports:
      - "8881:8080"
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"


  apache:
    image: ubuntu/apache2
    volumes:
      - /srv/docker/angular/UNDECIDED-UI/apache.conf:/etc/apache2/sites-enabled/001-page.conf
      - /srv/docker/angular/UNDECIDED-UI/dist/UI
    ports:
      - "80:80"
    labels:
      - "traefik.http.routers.apache.rule=PathPrefix(`/`)"

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "81:80"
      - "8889:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
